trigger: none
pr: none

parameters:
  - name: profile
    displayName: 'Elige un perfil (prod / dev / stage)'
    type: string
    default: dev
    values:
      - dev
      - stage
      - prod

variables:
  # Azure Service Connection for AKS and other Azure resources
  azureSubscription: 'ecommerce-terraform-sc'
  # Docker Hub Service Connection
  dockerHubServiceConnection: 'ecommerce-docker'
  
  # Environment variables
  RESOURCE_GROUP: 'rg-${{ parameters.profile }}'
  CLUSTER_NAME: 'aks-${{ parameters.profile }}'
  K8S_MANIFEST_DIR: 'k8s'
  IMAGE_TAG_SUFFIX: ':0.1.0'
  TRIVY_SEVERITY_THRESHOLD: 'HIGH,CRITICAL' # Fail pipeline if HIGH or CRITICAL vulnerabilities are found
  TRIVY_EXIT_CODE: '1' # Exit with 1 if issues are found for vulnerabilities or misconfigs


pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Checkout
    displayName: 'Checkout Source Code'
    jobs:
      - job: CheckoutJob
        steps:
          - checkout: self
            displayName: 'Checkout repository'

  - stage: SonnarQubeAndBuild
    displayName: 'Build Project'
    jobs:
      - job: SonnarAndBuildJob
        steps:
          - task: SonarCloudPrepare@3
            inputs:
              SonarQube: 'ecommerce-sonar-qube'
              organization: 'brayan-organization'
              scannerMode: 'other'
              extraProperties: |
                sonar.projectKey=brayan-organization_First-pipeline
                sonar.projectName=First pipeline
          - task: Maven@4
            inputs:
              azureSubscription: 'ecommerce-terraform-sc'
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true

  - stage: UnitAndIntegrationTests
    displayName: 'Run Unit and Integration Tests'
    jobs:
      - job: TestJob
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'ecommerce-terraform-sc'
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests=false'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  - stage: BuildAndPushDockerImages
    displayName: 'Build and Push Docker Images'
    jobs:
      - job: DockerJob
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'ecommerce-terraform-sc'
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: Docker@2
            displayName: 'Login to Docker Hub'
            inputs:
              containerRegistry: $(dockerHubServiceConnection)
              command: 'login'
          - script: |
              docker compose -f compose.yml build
            displayName: 'Build and Push Docker Images with Docker Compose'
          - script: |
              echo "Installing Trivy..."
              sudo apt-get update
              sudo apt-get install -y wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
              sudo apt-get update
              sudo apt-get install -y trivy
              trivy --version
            displayName: 'Install Trivy'
          - script: |
              echo "Scanning Docker Images with Trivy..."
              declare -A service_images
              service_images["cloud-config-container"]="kenbra/cloud-config-ecommerce-boot"
              service_images["api-gateway-container"]="kenbra/api-gateway-ecommerce-boot"
              service_images["proxy-client-container"]="kenbra/proxy-client-ecommerce-boot"
              service_images["order-service-container"]="kenbra/order-service-ecommerce-boot"
              service_images["payment-service-container"]="kenbra/payment-service-ecommerce-boot"
              service_images["product-service-container"]="kenbra/product-service-ecommerce-boot"
              service_images["shipping-service-container"]="kenbra/shipping-service-ecommerce-boot"
              service_images["user-service-container"]="kenbra/user-service-ecommerce-boot"
              service_images["favourite-service-container"]="kenbra/favourite-service-ecommerce-boot"
              SCAN_FAILED=false
              for service_name in "${!service_images[@]}"; do
                  image_name="${service_images[$service_name]}$(IMAGE_TAG_SUFFIX)"
                  echo "--- Scanning image: $image_name ---"
              done
            displayName: 'Scan Docker Images with Trivy'
            condition: succeeded()
          - script: |
              docker compose -f compose.yml push
          - task: Docker@2
            displayName: 'Logout from Docker Hub'
            inputs:
              containerRegistry: $(dockerHubServiceConnection)
              command: 'logout'
            condition: succeededOrFailed()

  - stage: DeployToAKS
    displayName: 'Configure kubectl and deploy to AKS'
    jobs:
      - job: DeployJob
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'ecommerce-terraform-sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(CLUSTER_NAME) --overwrite-existing'

          - task: KubernetesManifest@1
            displayName: 'Apply Zipkin Manifest'
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'ecommerce-terraform-sc'
              azureResourceGroup: '$(RESOURCE_GROUP)'
              kubernetesCluster: '$(CLUSTER_NAME)'
              namespace: 'default'
              manifests: '$(K8S_MANIFEST_DIR)/zipkin.yaml'
          - script: |
              echo "Waiting for Zipkin to be healthy..."
              kubectl wait --for=condition=Ready pod -l app=zipkin-app -n default --timeout=5m
            displayName: 'Wait for Zipkin to be Healthy'
            condition: succeeded()

          - task: KubernetesManifest@1
            displayName: 'Apply Service Discovery Manifest'
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'ecommerce-terraform-sc'
              azureResourceGroup: '$(RESOURCE_GROUP)'
              kubernetesCluster: '$(CLUSTER_NAME)'
              namespace: 'default'
              manifests: '$(K8S_MANIFEST_DIR)/service-discovery.yaml'
          - script: |
              echo "Waiting for Service Discovery to be healthy..."
              kubectl wait --for=condition=Ready pod -l app=service-discovery-app -n default --timeout=5m
            displayName: 'Wait for Service Discovery to be Healthy'
            condition: succeeded()

          - task: KubernetesManifest@1
            displayName: 'Apply Cloud Config Manifest'
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'ecommerce-terraform-sc'
              azureResourceGroup: '$(RESOURCE_GROUP)'
              kubernetesCluster: '$(CLUSTER_NAME)'
              namespace: 'default'
              manifests: '$(K8S_MANIFEST_DIR)/cloud-config.yaml'
          - script: |
              echo "Waiting for Cloud Config to be healthy..."
              kubectl wait --for=condition=Ready pod -l app=cloud-config-app -n default --timeout=5m
            displayName: 'Wait for Cloud Config to be Healthy'
            condition: succeeded()