version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    build:
      context: ./service-discovery
    image: kenbra/service-discovery-ecommerce-boot:stage
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      zipkin-container:
        condition: service_started
  cloud-config-container:
    build:
      context: ./cloud-config
    image: kenbra/cloud-config-ecommerce-boot:stage
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=cloud-config-container
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9296/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  api-gateway-container:
    build:
      context: ./api-gateway
    image: kenbra/api-gateway-ecommerce-boot:stage
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=api-gateway-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  proxy-client-container:
    build:
      context: ./proxy-client
    image: kenbra/proxy-client-ecommerce-boot:stage
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=proxy-client-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  order-service-container:
    build:
      context: ./order-service
    image: kenbra/order-service-ecommerce-boot:stage
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=order-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  payment-service-container:
    build:
      context: ./payment-service
    image: kenbra/payment-service-ecommerce-boot:stage
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=payment-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  product-service-container:
    build:
      context: ./product-service
    image: kenbra/product-service-ecommerce-boot:stage
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=product-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  shipping-service-container:
    build:
      context: ./shipping-service
    image: kenbra/shipping-service-ecommerce-boot:stage
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=shipping-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  user-service-container:
    build:
      context: ./user-service
    image: kenbra/user-service-ecommerce-boot:stage
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=user-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  favourite-service-container:
    build:
      context: ./favourite-service
    image: kenbra/favourite-service-ecommerce-boot:stage
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=favourite-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started