apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - port: 8400
      targetPort: 8400
      nodePort: 30400
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:        
        - name: payment-service
          image: kenbra/payment-service-ecommerce-boot:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8400          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:9411/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "payment-service"
            - name: LOGGING_LEVEL_IO_GITHUB_RESILIENCE4J
              value: DEBUG
          readinessProbe:
            httpGet:
              path: /payment-service/actuator/health
              port: 8400
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /payment-service/actuator/health
              port: 8400
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3