apiVersion: v1
kind: Service
metadata:
  name: proxy-client
spec:
  type: NodePort
  selector:
    app: proxy-client
  ports:
    - port: 8900
      targetPort: 8900
      nodePort: 30890
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
        - name: proxy-client
          image: kenbra/proxy-client-ecommerce-boot:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8900          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:9411/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "proxy-client"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CACHE
              value: TRACE
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CACHE_INTERCEPTOR
              value: TRACE            
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              value: DEBUG
            - name: LOGGING_LEVEL_IO_GITHUB_RESILIENCE4J
              value: DEBUG
            - name: FEATURES_CACHE_ENABLED
              value: "true"
            - name: FEATURES_RETRY_ENABLED
              value: "true"
