apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  type: NodePort
  selector:
    app: service-discovery
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: kenbra/service-discovery-ecommerce-boot:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8761          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:9411/"
            - name: EUREKA_INSTANCE
              value: "service-discovery"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
