apiVersion: v1
kind: Service
metadata:
  name: cloud-config
spec:
  type: ClusterIP
  selector:
    app: cloud-config
  ports:
    - port: 9296
      targetPort: 9296
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      initContainers:
        - name: wait-for-service-discovery
          image: busybox:1.28
          command: ['sh', '-c', 'until wget -T 5 -q -O- http://service-discovery:8761/actuator/health; do echo "Waiting for service-discovery"; sleep 10; done;']
        - name: wait-for-zipkin
          image: busybox:1.28
          command: ['sh', '-c', 'until wget -T 5 -q -O- http://zipkin:9411/health; do echo "Waiting for zipkin"; sleep 10; done;']
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo "Waiting for rabbitmq"; sleep 10; done;']
      containers:
        - name: cloud-config
          image: kenbra/cloud-config-ecommerce-boot:0.1.0
          ports:
            - containerPort: 9296          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "cloud-config"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
