apiVersion: v1
kind: Service
metadata:
  name: favourite-service
spec:
  type: NodePort
  selector:
    app: favourite-service
  ports:
    - port: 8800
      targetPort: 8800
      nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
        - name: favourite-service
          image: kenbra/favourite-service-ecommerce-boot:0.1.0
          ports:
            - containerPort: 8800          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "favourite-service"
