apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 8500
      targetPort: 8500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: selimhorri/product-service-ecommerce-boot:0.1.0
          ports:
            - containerPort: 8500
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
